// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SabemiTec.Persistence;

#nullable disable

namespace SabemiTec.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909175726_initial-create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SabemiTec.Entities.LogEventosBrutos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContratoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text");

                    b.Property<string>("PayloadBruto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusProcessamento")
                        .HasColumnType("integer");

                    b.Property<string>("StatusRecebido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId")
                        .IsUnique();

                    b.ToTable("LogsEventosBrutos");
                });

            modelBuilder.Entity("SabemiTec.Entities.StatusDoContrato", b =>
                {
                    b.Property<string>("ContratoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorUltimoPagamento")
                        .HasColumnType("numeric");

                    b.HasKey("ContratoId");

                    b.ToTable("StatusDosContratos");
                });
#pragma warning restore 612, 618
        }
    }
}
